# Form implementation generated from reading ui file 'ViewWindowUI.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewWindow(object):
    def setupUi(self, ViewWindow):
        ViewWindow.setObjectName("ViewWindow")
        ViewWindow.resize(405, 240)
        self.centralwidget = QtWidgets.QWidget(parent=ViewWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 391, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.TableNamesComboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.TableNamesComboBox.setObjectName("TableNamesComboBox")
        self.verticalLayout.addWidget(self.TableNamesComboBox)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.editButtonshorizontalLayout = QtWidgets.QHBoxLayout()
        self.editButtonshorizontalLayout.setObjectName("editButtonshorizontalLayout")
        self.addRowpushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.addRowpushButton.setObjectName("addRowpushButton")
        self.editButtonshorizontalLayout.addWidget(self.addRowpushButton)
        self.deleteRowpushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.deleteRowpushButton.setObjectName("deleteRowpushButton")
        self.editButtonshorizontalLayout.addWidget(self.deleteRowpushButton)
        self.SavepushButton = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.SavepushButton.setObjectName("SavepushButton")
        self.editButtonshorizontalLayout.addWidget(self.SavepushButton)
        self.verticalLayout.addLayout(self.editButtonshorizontalLayout)
        ViewWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=ViewWindow)
        self.statusbar.setObjectName("statusbar")
        ViewWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ViewWindow)
        QtCore.QMetaObject.connectSlotsByName(ViewWindow)

    def retranslateUi(self, ViewWindow):
        _translate = QtCore.QCoreApplication.translate
        ViewWindow.setWindowTitle(_translate("ViewWindow", "MainWindow"))
        self.addRowpushButton.setText(_translate("ViewWindow", "Add Row"))
        self.deleteRowpushButton.setText(_translate("ViewWindow", "Delete Row"))
        self.SavepushButton.setText(_translate("ViewWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewWindow = QtWidgets.QMainWindow()
    ui = Ui_ViewWindow()
    ui.setupUi(ViewWindow)
    ViewWindow.show()
    sys.exit(app.exec())
